### ISSUE TITLE
Outdated Media files not cleared out

### ISSUE THREAD

**Issue by kuanmy** [mljar/mercury#297]
Hi! I face an issue where some outdated media files aren't being deleted, which can lead to more and more space being consumed as the app runs:

1) Files in `uploads-temp` folder
- It creates a new folder containing the file for each session, but after the session becomes inactive, it still remains.
2) HTML files in the `media/` folder
- Every time I restart the app, it creates new HTML files for each .ipynb, but the previous versions remain.
Example file structure:
```
media/
    main.html (The 1st version of HTML still remain)
    main_d0937.html (The 2nd version of HTML after restart app)
uploads-temp/
    4gd6RJGn5pLSuu8fqoRUB4/ (Uploaded files in inactive session still remain)
        3DLt6CoyYjPHN98cP8VLnV
    6Lg3inG2cgp76yojqAwq7H/  (Uploaded files in active session)
        dgkSqYVhhTfvUZpNDvyuaT
```

Is there any way to automatically clear these outdated files as the app runs? I do notice that the app seems to be doing a great job in automatically deleting the output files in `media/` folder as a session becomes inactive.

**Comment by pplonski** [comment]
Hi @kuanmy!

Thank you for reporting the issue. I will do my best to have this fixed in the next week.

Are you happy with the framework? Do you get nice web app with `mercury`? I'd love to learn more about your use case.

**Comment by kuanmy** [comment]
Hi @pplonski ! Yes, the framework suits my purpose very well, and the bugs I am concerned with so far are also addressed, thanks for the quick response!

For my use case, I have a `ipynb` file that allows user to upload files, user can interact with the data uploaded (e.g. view & filter), then download the result files. Initially, I put the code on google colab and uses `ipywidget` for the widgets, but the interface surely isn't user-friendly. As I have no experience in designing or hosting Python websites, I searched for some framework that can easily turn `ipynb` file into a website and allow interactive widgets, which is where I came across `mercury`. 

Overall, I am quite satisfied with how `mercury` helps segregate the handling for widgets, website frontend and backend, and also provides several ways to deploy to the server. After changing to use `mercury` framework, I get to simplify my code a lot without having to deal with the widget listeners and layout, and the areas that I am not familiar with are also well covered by `mercury` 👍 .

**Comment by pplonski** [comment]
Great! I'm very happy that you found it useful. I'm currently working on update of RunMercury.com website. May I use the below sentence as testimonial: 

> After changing to use mercury framework, I get to simplify my code a lot without having to deal with the widget listeners and layout

May I ask for your name, job title and company name? If you would like to stay anonymous, it's ok, I will use your GitHub username.  Thank you!

**Comment by kuanmy** [comment]
Sure 👌  you can use my Github username, thanks!

**Comment by codinggeeks06** [comment]
hey,
did this get resolved?
I am still getting issue in this. How to clear outdated media files?

**Comment by pplonski** [comment]
It might still be the issue. You can create some script to clear outdated media files.

**Comment by pplonski** [comment]
we are no longer using Django in mercury. The newest mercury is using Tornado, the same as Jupyter server.
